/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hjq_jni_myJni */

#ifndef _Included_com_hjq_jni_myJni
#define _Included_com_hjq_jni_myJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hjq_jni_myJni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hjq_jni_myJni_sayHello
  (JNIEnv *env, jclass jobj){

 //   int i = 10;
   // return (*env)->NewStringUTF(env, i + "123");
    return (*env)->NewStringUTF(env,"JNI 123");
 }

#ifdef __cplusplus
}
#endif
#endif
